services:
  - type: web
    name: mojilo-manish-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node dist/server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
